default_context:
  project_name: 'fake_api'
  project_slug: 'fake_api'
  domain_main: 'fake_api.com'
  domain_staging: 'stag.fake_api.com'
  docker_swarm_stack_name_main: 'fake_api-com'
  docker_swarm_stack_name_staging: 'stag-fake_api-com'
  secret_key: 'd76ee97a335203d1d2586762a832a33429b496c00e5b0b013ba475afb2f2b9c1'
  first_superuser: 'admin@admin.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fake_api.com", "https://stag.fake_api.com", "https://fake_api.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fake_api.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@admin.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'fake_api.com'
  traefik_constraint_tag_staging: 'stag.fake_api.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: 'fake_api'
  docker_image_backend: 'fake_api_backend'
  docker_image_celeryworker: 'fake_api_celery_worker'
  docker_image_frontend: 'fake_api_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
